### ISSUE TITLE
pyenv 안에서 torch gpu training 가능한지 체크

### ISSUE THREAD

**Issue by hyeon95y** [KU-BIG/nipa-connection-guide#10]

**Comment by hyeon95y** [comment]
1. 임의의 유저 계정 생성
- sudo 권한 주고 생성
- pyenv 설치후에
- sudo 권한 제거

2. pyenv에서 아래 듀토리얼 수행
- https://pytorch.org/tutorials/beginner/pytorch_with_examples.html
- gpu로 잘 수행되면 문제가 없는것

**Comment by yeeunsong** [comment]
anaconda 환경으로 이동
