### ISSUE TITLE
사용자용 가이드 작성

### ISSUE THREAD

**Issue by hyeon95y** [KU-BIG/nipa-connection-guide#13]
readme.md에 바로 업데이트 하거나
따로 작성

**Comment by hyeon95y** [comment]
11기를 위해서는 jupyterlab 설치하고 실행하는것도 필요해보이는데, 굳이 귀찮게 두번 작성하느니
wiki 링크를 거는것도 좋아보임.
다만 wiki에는 docker-specific한 내용이 있어서 바로 활용할수 있는지는 검토 필요

**Comment by jaewonalive** [comment]
> 11기를 위해서는 jupyterlab 설치하고 실행하는것도 필요해보이는데, 굳이 귀찮게 두번 작성하느니
> wiki 링크를 거는것도 좋아보임.
> 다만 wiki에는 docker-specific한 내용이 있어서 바로 활용할수 있는지는 검토 필요

지난 학기에 어려움을 겪었던 사람들이 많았던 경험에 비추어보면  wiki 링크만 걸어뒀을 때 바로 활용하기는 어려울 것 같습니다.

**Comment by hyeon95y** [comment]
1. 접속 가이드
- README.md 참고
-> 추후에 일원화 할 필요가 있어 보입니다 (@yeeunsong @jaewonalive )

1. 비밀번호 변경
반드시 기본 비밀번호에서 변경 부탁드립니다
```bash
[bible2@host1 bible2]$ passwd
Changing password for user bible2.
Changing password for bible2
(current) UNIX password:  (기존의 패스워드입력)
New password: (새로운 패스워드 입력)
Retype new password: (새로운 패스워드 재입력)
passwd: all authentication tokens updated successfully.
[bible2@host1 bible2]$
```

1. pyenv 설치
- pyenv : 관리자 권한(root)없이 원하는 python 버전을 사용하기 위한 도구
- pyenv-virtualenv : 격리된 파이썬 실행환경을 만들어줌. 패키지 사이의 충동을 막을수 있고, 전역 환경에 불필요한 패키지를 설치하지 않아도 됨. 여러명이서 서버를 사용하기 위하여 반드시 필요한 환경. 
```bash
$ git clone https://github.com/pyenv/pyenv.git ~/.pyenv
$ echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.profile
$ echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.profile
$ echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.profile
$ source ~/.profile
$ git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
```

2. 파이썬 설치
```bash
$ pyenv install 3.7.3
```

3. 사용할 버전 지정
```bash
$ pyenv global 3.7.3  # 항상 이 버전을 사용
$ pyenv shell 3.7.3  # 이 세션에서만 사용
```

4. virtual env 생성
```bash
$ pyenv virtualenv [venv 이름]
```

5. virtual env 목록 확인
```bash
$ pyenv virtualenvs
```

6. virtual env 진입
```bash
$ pyenv activate [venv 이름]
```

7. 사용
```bash
([venv 이름]) pip3 install jupyterlab
([venv 이름]) pip3 install sklearn
```

**Comment by hyeon95y** [comment]
@jaewonalive @yeeunsong 
pyenv 밖의 전역에 무언가를 깔지 말라. 혹은 못하게 하는 장치가 필요할듯

**Comment by hyeon95y** [comment]
가장 간단하게는 파이썬 삭제? 근데 이 경우에 pyenv에 어떻게 영향을 주는지 모르겠음
어차피 sudo 권한 없어서 전역에는 뭐 깔기 힘들거 같기는 한데.. 그래도 아예 삭제해놓는게 낫지 않나

**Comment by hyeon95y** [comment]
reame.md에 있는 버전이 최신으로 업데이트됨
