### ISSUE TITLE
port 이슈 고민

### ISSUE THREAD

**Issue by hyeon95y** [KU-BIG/nipa-connection-guide#16]
Q. 같은 포트로 여러명이 접속해서, 포트포워딩을 다르게 할 경웨 쓰는데 문제가 없으면 포트를 하나만 열어도 되지 않을까?

e.g.)
사용자 A 는 포트 10000으로 접속, 8888에 jupyterlab을 실행하고 8888을 포트포워딩하여 사용
사용자 B 도 포트 10000으로 접속, 9999에 jupyterlab을 실행하고 9999를 포트포워딩하여 사용

위 시나리오에서 문제가 없을 경우 굳이 여러 포트를 열 필요가 없음 (보안에 취약해짐)
@yeeunsong  @jaewonalive  이것도 고려해봐야 할듯

**Comment by jaewonalive** [comment]
> Q. 같은 포트로 여러명이 접속해서, 포트포워딩을 다르게 할 경웨 쓰는데 문제가 없으면 포트를 하나만 열어도 되지 않을까?
> 
> e.g.)
> 사용자 A 는 포트 10000으로 접속, 8888에 jupyterlab을 실행하고 8888을 포트포워딩하여 사용
> 사용자 B 도 포트 10000으로 접속, 9999에 jupyterlab을 실행하고 9999를 포트포워딩하여 사용
> 
> 위 시나리오에서 문제가 없을 경우 굳이 여러 포트를 열 필요가 없음 (보안에 취약해짐)
> @yeeunsong @jaewonalive 이것도 고려해봐야 할듯

이게 가능할 경우에는 포트포워딩을 각자 몇번으로 할지 약속해야할 거 같은데 맞나요?

**Comment by hyeon95y** [comment]
@jaewonalive 8888을 쓰지 말라는 얘기만 해도, 다들 각자 알아서 port를 찾을텐데 겹칠 일은 잘 없을것 같습니다(다섯자리 숫자를 임의로 찍었는데, 그 두개가 같을 확률은..)

**Comment by yeeunsong** [comment]
> Q. 같은 포트로 여러명이 접속해서, 포트포워딩을 다르게 할 경웨 쓰는데 문제가 없으면 포트를 하나만 열어도 되지 않을까?
> 
> e.g.)
> 사용자 A 는 포트 10000으로 접속, 8888에 jupyterlab을 실행하고 8888을 포트포워딩하여 사용
> 사용자 B 도 포트 10000으로 접속, 9999에 jupyterlab을 실행하고 9999를 포트포워딩하여 사용
> 
> 위 시나리오에서 문제가 없을 경우 굳이 여러 포트를 열 필요가 없음 (보안에 취약해짐)
> @yeeunsong @jaewonalive 이것도 고려해봐야 할듯



여러명이 같은 포트로 접속, 포트포워딩 다른 경우가 가능하네요.
그리고 포트포워딩이 같은 경우도 매우 희박하네요 (99999같이 인기 있는? 것만 많이 쓰지 않으면..)

**Comment by hyeon95y** [comment]
해결됨
