### ISSUE TITLE
keras 사용시 오류 문제 해결

### ISSUE THREAD

**Issue by yeeunsong** [KU-BIG/nipa-connection-guide#18]
서버에서 keras 사용시 오류 발생
keras에서 dense, simple rnn은 문제 없음. cnn 쓰려니까 오류 발생

**Comment by yeeunsong** [comment]
cuDNN과의 호환성 문제일 가능성도 존재

현재 버전
```
cuDNN v7.5.1 (April 22, 2019), for CUDA 10.1, 10.0, 9.2, 9.0, 8.0
```

**Comment by jaewonalive** [comment]
cuDNN을 삭제하고 7.6이상 버전을 설치하면 되지 않을까요?
삭제하는 방법은 제가 모르겠지만 아래에 설치하는 방법은 찾았습니다.

https://dreamgonfly.github.io/2017/12/17/deeplearning-server-setting.html

**Comment by jaewonalive** [comment]
cuDNN version swticher

https://github.com/dnzzcn/cuDNNv

**Comment by jaewonalive** [comment]
> cuDNN과의 호환성 문제일 가능성도 존재
> 
> 현재 버전
> 
> ```
> cuDNN v7.5.1 (April 22, 2019), for CUDA 10.1, 10.0, 9.2, 9.0, 8.0
> ```

cuDNN v7.5.1과 호환이 되는 tensorflow 버전 사용함으로써 문제 해결.
pip install tensorflow 실행시 tensorflow2.0이 설치됨.
설치된 tensorflow2.0 삭제후 1.15rc2버전으로 설치해주고 keras이용해서 cnn 모델 학습시키니 잘된다.
1.15rc2버전에 cpu와 gpu버전이 모두 포함돼있음.

```
pip uninstall tensorflow
pip install tensorflow==1.15rc2
```

**Comment by yeeunsong** [comment]
재원오빠가 해결했으므로 닫습니다.
