### ISSUE TITLE
여러 개의 kernel 접속시 서버가 죽는 이유 알아내기

### ISSUE THREAD

**Issue by yeeunsong** [KU-BIG/nipa-connection-guide#19]
커널 여러개 동시에 켜놓고 실행 하면 서버가 죽는 상황 발생, 
어떤 이유때문에 서버가 죽는지 알아내기

메모리 문제일 가능성
- 파이썬 및 커널 자체에서 감당할 수 있는 메모리 상한 존재   
- htop으로 확인중

**Comment by jaewonalive** [comment]
VIRT(프로세스가 사용중인 가상 메모리양) 부분이 빨간색 글씨로 나옵니다.
24.1G와 54.3G가  등장합니다. 

![htop](https://user-images.githubusercontent.com/52857057/79003443-95ad7700-7b8d-11ea-811f-668caadebc11.JPG)
