### ISSUE TITLE
Issue 관리 협업 익히기

### ISSUE THREAD

**Issue by hyeon95y** [KU-BIG/nipa-connection-guide#3]
분석, 관리, 협업 등에 용이한 방법이라 잘 익히고 프로젝트할때 전파하면 좋을것 같음

1. 프로젝트 사용시
- 멤버들 모두 contributor로 해당 repo에 등록
- 해야 할 todo를 issues에 작성
- branch 따서 해당 내용 작업
- master에 merge하여 진행된 작업 반영

2. 그러기 위해서 우리가 알아야 하는 issue 사용법
- Create New Issue : 해야할 TO-DO 작성 (실행가능한 가능한 작은 단위로. 
    e.g.) EDA 진행 (x)
    e.g.) 변수 그룹 A간의 correlation 확인 (o) , linear regression 성능 확인(o)
- Labels : 이슈의 성질에 대해 간단하게 정의 (e.g.) documentation, bug, ... )
- Assigness : 해당 이슈를 수행할 사람을 지정

**Comment by yeeunsong** [comment]
issue 닫습니다
