### ISSUE TITLE
서버 계정 생성/관리용 툴 조사 

### ISSUE THREAD

**Issue by hyeon95y** [KU-BIG/nipa-connection-guide#4]
필요성
- 명령어로 계정 생성/삭제 등 관리 할수 있지만.. 어려움 / 귀찮음
- 서버 사용량 모니터링 또한 명령어로 할 수 있지만.. 어려움 / 귀찮음
- GUI 필요

아래 여러 후보중(Linux Server Tool로 검색한 내용)에서 
https://www.cyberciti.biz/tips/top-linux-monitoring-tools.html
https://geekflare.com/linux-tools-for-sysadmin/

아래 두가지 조건을 만족해야 함
- 계정 관리(추가/삭제)를 GUI로 편하게 할 수 있음
- 서버 사용량 모니터링을 GUI로 편하게 할 수 있음
- Free Plan이어야 함

Local에서 Docker Image 생성하여 거기다가 테스트 한 뒤에 nipa server에 적용

**Comment by hyeon95y** [comment]
이전에 ebb에 서버 공유하면서 작성한 내용이 command로 하는 방법 모아둔게 있었는데 어딨는지 못찾겠음..

```bash
useradd [유저명]

[유저명] ALL=(ALL)NOPASSWD:ALL
```

https://arrkaize86.tistory.com/entry/리눅스-유저User-생성-삭제-수정-방법

**Comment by yeeunsong** [comment]
https://cockpit-project.org/

cockpit으로 시도해보겠습니다.
- 무료
- can monitor/administer several servers at a same time

**Comment by hyeon95y** [comment]
http://blog.servis.co.kr/index.php/2019/01/29/centos7-cockpit/
https://blog.zvdev.com/2020/03/13/centos8-cockpit-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80%EC%97%90%EC%84%9C-%EC%84%9C%EB%B2%84-%EA%B4%80%EB%A6%AC/

**Comment by hyeon95y** [comment]
이거보고 설치했음

https://www.hackthesec.co.in/2017/01/how-to-install-cockpit-on-ubuntu-1604.html

cockpit 실행방법

```bash
$ systemctl start cockpit.socket
$ systemctl enable cockpit.socket
```

브라우저에서 접속
```bash
localhost:9090
```

9090이 기본포트이므로, ssh 연결할때 아래와같이 포트포워딩
```bash
$ ssh -L 9090:localhost:9090 [id]@[ip] -p [port]
```

**Comment by hyeon95y** [comment]
해당 process를 kill하지 않으면 재부팅하기 전까지는 계속 돌아가는듯 (실행 명령어를 다시 실행하지 않아도, 연결만 되어있으면 localhost:9090으로 접속 가능함)

**Comment by hyeon95y** [comment]
사용 가이드

[새 사용자 추가]
1) 계정 생성
- Accounts - Create New Account
- [First name].[Last name]
- password : 
2) 사용자별 폴더 생성 : 접속시 여기로 리다이렉트됨]
$ cd /home
$ sudo mkdir [First name].[Last name]
3) sudo 권한 주는법 (필요할 시)
$ sudo usermod -aG sudo [id]

**Comment by hyeon95y** [comment]
완료되었으므로 닫습니다

**Comment by yeeunsong** [comment]
cockpit 초기 로그인 할 때  'Reuse my password for privileged tasks' 체크박스에 체크를 하지 않으면 account를 managing할 때 아래와 같은 문구가 뜬다.

```
Not permitted to perform this action
```

가 뜨는 경우가 있다.

이럴 때는 cockpit에 다시 접속해서 재로그인 필요.
재로그인 시 'Reuse my password for privileged tasks' 체크박스에 체크를 하면 정상적으로 접속가능.

로그인시 체크박스에 체크를 하지 않으면 unprivileged interface를 갖게 되는듯. 체크문구의 뜻을 약간 모호하게 해놓은것 같다

참고:
https://github.com/cockpit-project/cockpit/issues/9352
