### ISSUE TITLE
pyenv 설치 및 사용법 documentation

### ISSUE THREAD

**Issue by hyeon95y** [KU-BIG/nipa-connection-guide#5]
- pyenv 설치하여 여러 사람이 각각의 python environment로 사용할수 있도록 세팅
- pyenv 사용법 documentation

**Comment by hyeon95y** [comment]
- 16.04 specific한 문제인지, 기존 document대로 설치했을때 설치되지 않는 문제 있음
- anaconda dependency 때문일수도 있다는 생각이 들어 삭제 진행중(#9 )

**Comment by hyeon95y** [comment]
ubuntu (sudo계정)에서 테스트됨

sudo권한 없는 계정에서 어떻게 동작하는지 확인 필요
(@yeeunsong yeeun.song 계정 sudo권한 없이 만들어서 아래 제대로 수행되는지 확인점!)

1. 유저가 설치
```bash
$ git clone https://github.com/pyenv/pyenv.git ~/.pyenv
$ echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.profile
$ echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.profile
$ echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.profile
$ source ~/.profile
$ git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
```

2. 관리자가 설치해줘야 하는 부분
```bash
$ sudo apt-get install -y libsqlite3-dev zlib1g-dev libssl-dev libffi-dev
$ sudo apt-get install -y python3-setuptools python3-pip
 
```

3. 파이썬 설치
```bash
$ pyenv install 3.7.3
```

4. 사용할 버전 지정
```bash
$ pyenv global 3.7.3  # 항상 이 버전을 사용
$ pyenv shell 3.7.3  # 이 세션에서만 사용
```

5. virtual env 생성
```bash
$ pyenv virtualenv [venv 이름]
```

6. virtual env 목록 확인
```bash
$ pyenv virtualenvs
```

7. virtual env 진입
```bash
$ pyenv activate [venv 이름]
```

8. 사용
```bash
 pip3 install jupyterlab
 pip3 install sklearn
```

9. jupyterlab 실행
```bash
 jupyter lab --port=[포트포워딩한 포트2] 
```

**Comment by hyeon95y** [comment]
관리자 설치 부분이 sudo권한 없이 제대로 동작하지 않을 경우(=유저가 혼자서 sudo권한 없이 pyenv 설치를 할 수 없을 경우), 계정 생성 하면서 관리자가 pyenv 설치까지 해줘야 할듯

**Comment by yeeunsong** [comment]
@hyeon95y 2번의 관리자가 설치해야 하는 부분

```
$ sudo apt-get install -y libsqlite3-dev zlib1g-dev libssl-dev libffi-dev
$ sudo apt-get install -y python3-setuptools python3-pip
```
은 계정을 다시 변경해서 (sudo 권한 없는 것에서 있는걸로) ,
지금 설치중인 directory에 들어가서 설치하면 되는건가요?

**Comment by hyeon95y** [comment]
@yeeunsong 

- 계정을 변경한다기 보다는(yeeun.song -> root)가 아닌, 권한을 변경해서 (cockpit에서 administrator 체크해서 변경가능, 혹은 명령어로 sudo권한 부여가능) 진행하는 것입니다.
- 해당 계정에서 설치하여야 합니다

우선은 해당 계정에서 sudo 권한 없이 설치해보고 되면 제일 좋고, 안되면 번거로운 과정(sudo를 줘서 설치했다가 다시 뺏었다가)를 거쳐야 할듯.

후자의 경우에 계정 생성만 하고 넘겨주었을때 user가 스스로 환경 셋업이 불가능하므로, 계정을 생성할때마다 pyenv를 설치하고 user에게 넘겨주는 번거로운 작업이 필요함

**Comment by yeeunsong** [comment]
cockpit에서 account를 생성했을 때와 local에서 adduser를 통해 계정을 생성했을 때 각각 결과가 다르게 나타난다. 

1. cockpit 내부에서 account를 생성후, terminal에서 pyenv 동작하는지 확인
1번의 

```
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
```
를 시도하니

```
 fatal: could not create leading directories of '/home/yeeun.song/.pyenv': Permission denied  
```
라고 에러가 뜬다.


2. local terminal에서 adduser를 통해 계정 생성, terminal에서 pyenv 동작하는지 확인
1번의 

```
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
```
를 시도하니

문제없이 생성됨.


cockpit에서 account를 생성할 때 설정을 다르게 주어야 하는건지, 아니면 권한의 차이가 있는건지 알아봐야 할 것 같다.

**Comment by hyeon95y** [comment]
@yeeunsong cockpit에서 administrator 권한 줘도 같은 문제가 일어나나여?

**Comment by hyeon95y** [comment]
11기(12기?)에게 배포하기 전에, 운영진들 대상으로 한번 잘 돌아가는지 계정 주고 테스트해봐야할듯

**Comment by yeeunsong** [comment]
pyenv에서 파이썬 설치할 때 오류가 나는 경우   


```
$ pyenv install 3.7.3
````
에서 

```
Command 'pyenv' not found, did you mean:                                                     
                                                                                             
  command 'pyvenv' from deb python3-venv                                                     
  command 'p7env' from deb libnss3-tools                                                     
                                                                                             
Try: sudo apt install <deb name>   
```


라는 에러 메세지가 뜨면 패스에 오류가 생긴 것으로 수정을 해주어야 한다.

```
$ export PATH="~/.pyenv/bin:$PATH"
$ eval "$(pyenv init -)"
$ eval "$(pyenv virtualenv-init -)"
```

수정 후에 정상적으로 파이썬 설치가 완료됨.   

https://www.pythonanywhere.com/forums/topic/13632/
https://github.com/pyenv/pyenv-virtualenv/issues/233

**Comment by hyeon95y** [comment]
> ubuntu (sudo계정)에서 테스트됨
> 
> sudo권한 없는 계정에서 어떻게 동작하는지 확인 필요
> (@yeeunsong yeeun.song 계정 sudo권한 없이 만들어서 아래 제대로 수행되는지 확인점!)
> 
> 1. 유저가 설치
> 
> ```shell
> $ git clone https://github.com/pyenv/pyenv.git ~/.pyenv
> $ echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.profile
> $ echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.profile
> $ echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.profile
> $ source ~/.profile
> $ git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
> ```
> 
> 1. 관리자가 설치해줘야 하는 부분
> 
> ```shell
> $ sudo apt-get install -y libsqlite3-dev zlib1g-dev libssl-dev libffi-dev
> $ sudo apt-get install -y python3-setuptools python3-pip
>  
> ```
> 
> 1. 파이썬 설치
> 
> ```shell
> $ pyenv install 3.7.3
> ```
> 
> 1. 사용할 버전 지정
> 
> ```shell
> $ pyenv global 3.7.3  # 항상 이 버전을 사용
> $ pyenv shell 3.7.3  # 이 세션에서만 사용
> ```
> 
> 1. virtual env 생성
> 
> ```shell
> $ pyenv virtualenv [venv 이름]
> ```
> 
> 1. virtual env 목록 확인
> 
> ```shell
> $ pyenv virtualenvs
> ```
> 
> 1. virtual env 진입
> 
> ```shell
> $ pyenv activate [venv 이름]
> ```
> 
> 1. 사용
> 
> ```shell
> ([venv 이름]) pip3 install jupyterlab
> ([venv 이름]) pip3 install sklearn
> ```

여기서 2.(관리자가 설치해줘야 하는 부분) 를 0.으로 바꿔서, 새 계정이 생성되었을때에 관리자가 저것만 설치해주고 나머지는 유저가 직접 설치하게 해도 되지 않을까? (나머지 부분이 sudo 없이 설치가 가능하다면)

**Comment by yeeunsong** [comment]
sudo권한 없는 계정에서 어떻게 동작하는지 확인작업

local(ubuntu)에서 계정 생성
cockpit으로 들어가서 실행

중간에 administer 권한을 cockpit에서 줘서  install 진행

```
$ sudo apt-get install -y libsqlite3-dev zlib1g-dev libssl-dev libffi-dev
$ sudo apt-get install -y python3-setuptools python3-pip
```


다시 adminster 권한 제거하고 

뒤에 설치 진행

virtualenv 진입 후 실행까지 성공적으로 실행됨.

다만 cockpit에서 만든 계정을 어떻게해야할지 봐야할듯!

**Comment by yeeunsong** [comment]
> @yeeunsong cockpit에서 administrator 권한 줘도 같은 문제가 일어나나여?

넵. admin 권리 여부와 상관없이 같은 에러가 뜹니다.

**Comment by hyeon95y** [comment]
@yeeunsong ubuntu 계정으로 할때는 안떴던것 같은데.. 
무튼 저 줄을 가이드에 포함시키면 해결할수 있는걸로 이해했는데, 맞나요?

**Comment by yeeunsong** [comment]
> @yeeunsong ubuntu 계정으로 할때는 안떴던것 같은데..
> 무튼 저 줄을 가이드에 포함시키면 해결할수 있는걸로 이해했는데, 맞나요?

```
Command 'pyenv' not found, did you mean:                                                     
                                                                                             
  command 'pyvenv' from deb python3-venv                                                     
  command 'p7env' from deb libnss3-tools                                                     
                                                                                             
Try: sudo apt install <deb name>   
`````
이 예시 말하는 건가요?


이 에러가 뜨면 

터미널에서 

```
$ export PATH="~/.pyenv/bin:$PATH"
$ eval "$(pyenv init -)"
$ eval "$(pyenv virtualenv-init -)"
```
를 입력해주면 됩니다.

**Comment by jaewonalive** [comment]
> 11기(12기?)에게 배포하기 전에, 운영진들 대상으로 한번 잘 돌아가는지 계정 주고 테스트해봐야할듯

운영진들이라고 당장 서버를 쓸 일이 있는 사람들은 아니니까 회원들 중에서 당장 서버 있으면 쓸 거다 하시는 분들을 자원 받아보는 건 어떨까요?

**Comment by jaewonalive** [comment]
> ubuntu (sudo계정)에서 테스트됨
> 
> sudo권한 없는 계정에서 어떻게 동작하는지 확인 필요
> (@yeeunsong yeeun.song 계정 sudo권한 없이 만들어서 아래 제대로 수행되는지 확인점!)
> 
> 1. 유저가 설치
> 
> ```shell
> $ git clone https://github.com/pyenv/pyenv.git ~/.pyenv
> $ echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.profile
> $ echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.profile
> $ echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.profile
> $ source ~/.profile
> $ git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
> ```
> 
> 1. 관리자가 설치해줘야 하는 부분
> 
> ```shell
> $ sudo apt-get install -y libsqlite3-dev zlib1g-dev libssl-dev libffi-dev
> $ sudo apt-get install -y python3-setuptools python3-pip
>  
> ```
> 
> 1. 파이썬 설치
> 
> ```shell
> $ pyenv install 3.7.3
> ```
> 
> 1. 사용할 버전 지정
> 
> ```shell
> $ pyenv global 3.7.3  # 항상 이 버전을 사용
> $ pyenv shell 3.7.3  # 이 세션에서만 사용
> ```
> 
> 1. virtual env 생성
> 
> ```shell
> $ pyenv virtualenv [venv 이름]
> ```
> 
> 1. virtual env 목록 확인
> 
> ```shell
> $ pyenv virtualenvs
> ```
> 
> 1. virtual env 진입
> 
> ```shell
> $ pyenv activate [venv 이름]
> ```
> 
> 1. 사용
> 
> ```shell
> ([venv 이름]) pip3 install jupyterlab
> ([venv 이름]) pip3 install sklearn
> ```

7번으로 진입하고 나면 나면 자동으로 command에 ([venv 이름])이 붙네요. 7번 후 바로 8번 진입할 때는 command를 pip3부터 바로 쳐주면 됩니다.

**Comment by yeeunsong** [comment]
jupyterlab 브라우저에서 접속할때


1. 접속 시 '페이지가 작동하지 않습니다' 메세지가 뜨는 오류 발생시

- cmd 창의 링크 복붙하는 대신 localhost:[포트포워딩된 포트]를 브라우저에 입력하여 브라우저에서 접속




2. token/password입력없이 접속하는 방법

```
 jupyter lab --ip=0.0.0.0 --port=[포트포워딩한 포트] --NotebookApp.token='' --allow-root
```

**Comment by yeeunsong** [comment]
pyenv-virtualenv 밖에서 프로젝트를 실행하지 못하게 하는 방법 생각해봐야 할것 같습니다

#13 관련

**Comment by yeeunsong** [comment]
각각 계정마다 pyenv까지 설치해주는 것도 괜찮을 것 같습니다. 
pyenv-virtualenv 밖에서 작업하는 것 방지 + 사람들이 더욱 편하게 접속할 수 있도록

http://ehpub.co.kr/2-명령어를-작성한-파일을-실행-파일로-만들기/

**Comment by yeeunsong** [comment]
계정 생성하자마자 pyenv 한방에 까는법
by @hyeon95y 

1. 계정 생성
sudo adduser [username]
id : [username]
pw : Kub1gkorea!
- 생성후 Sever Administrator 꼭 체크!

2. 접속
ssh [username]@ip -p 27770
or
sudo su [username]
cd /home/[username]

3. pyenv 설치 (접속하자마자 실행)
sudo chmod +x /setup.sh
sudo mkdir /home/[username] <-- 이 부분은 생략, 계정 생성하자마자 만들어짐
sudo chmod -R 777 /home/[username]
/setup.sh [username] [사용할 파이썬 버전]


e.g.) /setup.sh usr.test4 3.6.5
kubig-venv 라는 이름으로 virtual env 실행됨
pyenv activate kubig-venv로 실행 가능

4. sudo 권한 해제
- Server Administrator uncheck



---
setup.sh 수정사항
1. chown $1:$1 .pyenv 추가
퍼미션 권한 주었음


---- 
참고 링크
https://conory.com/blog/19194
https://m.blog.naver.com/PostView.nhn?blogId=hj_veronica&logNo=220707938970&proxyReferer=https%3A%2F%2Fwww.google.com%2F
https://araikuma.tistory.com/117

**Comment by hyeon95y** [comment]
wiki에 있는 버전이 최종 버전으로 완료됨
