### ISSUE TITLE
프로젝트에서 서버 / 깃허브 기반 협업 세션/문서화

### ISSUE THREAD

**Issue by hyeon95y** [KU-BIG/nipa-connection-guide#6]
목적
- 프로젝트에서 서버 자원 활용
- 프로젝트에서 깃허브 레포 활용하여 이슈 기반의 협업

언제 한번 내가 운영진들한테 알려주고, 운영진들이 다시 한번 전파하는 방식으로..?

**Comment by yeeunsong** [comment]
혹은 세션 시간 전/후에 전체 학회원들에게 알려주는 방식도 좋을듯 하네요 (지난 학기에 도커/파이썬 설명했던 것처럼요)

**Comment by hyeon95y** [comment]
서버관리반(?)끼리는 잘 하고 있는것 같고, 이제 이걸 기반으로 잘 전파하면 될것 같습니다
