### ISSUE TITLE
ID/PW 관리/전달방법 고민

### ISSUE THREAD

**Issue by hyeon95y** [KU-BIG/nipa-connection-guide#8]

**Comment by yeeunsong** [comment]
10기&11기 카톡 공지방에 공지로 올리기?

**Comment by hyeon95y** [comment]
# 새 사용자 추가시 필요한 프로세스

## 계정 생성 
localhost:9090
Accounts - Create New Account
id(username) : [First name].[Last name] e.g) root.kim
password : [쿠빅 지정 패스워드]
sudo 권한 체크

## 사용자별 폴더 생성 : 접속시 여기로 리다이렉트됨]
$ cd /home
$ sudo mkdir [First name].[Last name]

## pyenv 설치
$ su [username]
$ ... (pyenv 설치) #5 

## sudo 권한 제거
localhost:9090
Administrator 체크 해제

## sudo 권한없이 pyenv 잘 작동하는지 확인
$ pyenv virtualenv kubig-venv
$ ... (python 잘 돌아가는지 테스트)

## sudo 권한 주는법 (필요할 시)
$ sudo usermod -aG sudo [id]
혹은 cockpit에서 server administrator 체크

**Comment by hyeon95y** [comment]
## 비밀번호 변경 방법
전달하여, 반드시 초기 비밀번호에서 바꿀것을 요구

```bash
[bible2@host1 bible2]$ passwd
Changing password for user bible2.
Changing password for bible2
(current) UNIX password:  (기존의 패스워드입력)
New password: (새로운 패스워드 입력)
Retype new password: (새로운 패스워드 재입력)
passwd: all authentication tokens updated successfully.
[bible2@host1 bible2]$
```

**Comment by jaewonalive** [comment]
한명 계정에 pyenv 설치할 때마다 시간이 얼마나 걸리나요?

> # 새 사용자 추가시 필요한 프로세스
> ## 계정 생성
> localhost:9090
> Accounts - Create New Account
> id(username) : [First name].[Last name] e.g) root.kim
> password : [쿠빅 지정 패스워드]
> sudo 권한 체크
> 
> ## 사용자별 폴더 생성 : 접속시 여기로 리다이렉트됨]
> $ cd /home
> $ sudo mkdir [First name].[Last name]
> 
> ## pyenv 설치
> $ su [username]
> $ ... (pyenv 설치) #5
> 
> ## sudo 권한 제거
> localhost:9090
> Administrator 체크 해제
> 
> ## sudo 권한없이 pyenv 잘 작동하는지 확인
> $ pyenv virtualenv kubig-venv
> $ ... (python 잘 돌아가는지 테스트)
> 
> ## sudo 권한 주는법 (필요할 시)
> $ sudo usermod -aG sudo [id]
> 혹은 cockpit에서 server administrator 체크

**Comment by jaewonalive** [comment]
> # 새 사용자 추가시 필요한 프로세스
> ## 계정 생성
> localhost:9090
> Accounts - Create New Account
> id(username) : [First name].[Last name] e.g) root.kim
> password : [쿠빅 지정 패스워드]
> sudo 권한 체크
> 
> ## 사용자별 폴더 생성 : 접속시 여기로 리다이렉트됨]
> $ cd /home
> $ sudo mkdir [First name].[Last name]
> 
> ## pyenv 설치
> $ su [username]
> $ ... (pyenv 설치) #5
> 
> ## sudo 권한 제거
> localhost:9090
> Administrator 체크 해제
> 
> ## sudo 권한없이 pyenv 잘 작동하는지 확인
> $ pyenv virtualenv kubig-venv
> $ ... (python 잘 돌아가는지 테스트)
> 
> ## sudo 권한 주는법 (필요할 시)
> $ sudo usermod -aG sudo [id]
> 혹은 cockpit에서 server administrator 체크

pyenv는 예은이가 테스트 해본 결과 sudo 권한 없이도 정상적으로 설치가 되는 걸 확인했으니까 여기서는 빠져도 될 것 같습니다.

**Comment by hyeon95y** [comment]
예은이가 테스트한 방법(카톡 참고)로 해결됨
